# Generated by Django 4.1.4 on 2022-12-25 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ('name',)},
        ),
    ]
